name: Deploy Hexo Blog

on:
  push:
    branches: [hexo]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1
          sparse-checkout: |
            /*
            !/achieve/*
            !/examples/*
          sparse-checkout-cone-mode: false
      # Install pandoc
      - name: Install pandoc
        run: |
          sudo apt update
          sudo apt install -y pandoc
          echo ${{ secrets.HEXO_DEPOLY_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        working-directory: blog
        run: npm ci
      - name: Deploy Pages
        working-directory: blog
        run: |
          npm run clean
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_branch: hexo-pages 
          folder: blog/public
          github_token: ${{ secrets.HEXO_DEPOLY_TOKEN }}
